-- MySQL Script generated by MySQL Workbench
-- Sáb 28 Fev 2015 19:36:49 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agence_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agence_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agence_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `agence_db` ;

-- -----------------------------------------------------
-- Table `agence_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agence_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(255) NULL,
  `role` VARCHAR(20) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agence_db`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agence_db`.`links` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url_link` TEXT NULL,
  `video` TINYINT(1) NULL DEFAULT 0,
  `status` CHAR(1) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_links_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_links_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `agence_db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agence_db`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agence_db`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agence_db`.`links_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agence_db`.`links_tags` (
  `links_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`links_id`, `tags_id`),
  INDEX `fk_links_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_links_has_tags_links1_idx` (`links_id` ASC),
  CONSTRAINT `fk_links_has_tags_links1`
    FOREIGN KEY (`links_id`)
    REFERENCES `agence_db`.`links` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_links_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `agence_db`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
